source 'https://rubygems.org'

gem 'activesupport', '~>5.2.2'
gem 'yajl-ruby', '1.4.1'
gem 'msgpack', '1.3.3'
gem 'fluentd', '1.4.2'
gem 'fluent-plugin-concat', '2.3.0'
gem 'fluent-plugin-detect-exceptions', '0.0.14'
gem 'elasticsearch', '7.5.0'
gem 'fluent-plugin-elasticsearch', '3.4.3'
gem 'minitest', '5.15.0'
gem 'public_suffix', '4.0.7'
gem 'jsonpath', '1.0.5'
gem 'kubeclient', '4.10.0'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.5.2'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-prometheus', '1.7.3'
gem 'fluent-plugin-systemd', '~>1.0.5'
gem 'oj', '3.10.8'
gem 'fluent-plugin-rewrite-tag-filter', '~>2.4.0'
gem 'fluent-plugin-kafka', '~>0.18.1'
gem 'extlz4', '~>0.3.3'
gem 'zstd-ruby', '~>1.5.5'
gem 'snappy', '~>0.3.0'
